version: '3.8'

services:
  app:
    build: ./Client/.
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./Client:/usr/src/app
      - /usr/src/app/node_modules

  electron-app:
    build: ./GUI-Client/.
    ports:
      - "3001:3001"
    env_file:
      - ./GUI-Client/.env
    environment:
      - NODE_ENV=production
      - SERVER_URL=${SERVER_URL}
      - USER_PROFILE=${USER_PROFILE}
      - VITE_DEV_SERVER_HOST=${VITE_DEV_SERVER_HOST}
      - VITE_DEV_SERVER_PORT=${VITE_DEV_SERVER_PORT:-3001}
    volumes:
      - ./GUI-Client:/usr/src/app
      - /usr/src/app/node_modules

  node-server:
    build: ./Server/.
    ports:
      - "8080:8080"
    env_file:
      - ./Server/.env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-8080}
      - EXECUTE_CYCLE_OFFSET=${EXECUTE_CYCLE_OFFSET:-}
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
